services:
  mysql:
    image: mysql:9.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kejiban
    volumes:
        -  mysql-data:/var/lib/mysql
        -  ./database/init:/docker-entrypoint-initdb.d 
volumes:
  mysql-data: